### ISSUE TITLE
Can't program ULX3S v3.0.8

### ISSUE THREAD

**Issue by nullobject** [emard/esp32ecp5#10]
I am having trouble programming the FPGA on a v3.0.8 board

I have copied the `blink_85f.bit` file onto the ESP32.

When I run:

```
import ecp5
ecp5.prog("blink_85f.bit")
```

then the blue LED lights, but nothing else happens and the board hangs. The FPGA doesn't appear to be programmed properly and the ESP32 becomes unresponsive with serial or FTP.

Any ideas what I am doing wrong?

I have already run `import ecp5setup` and configured WiFi etc.

**Comment by emard** [comment]
Something is not ok because after ecp5.prog("blink_85f.bit")
blue LED D22 should turn OFF and main LEDs D0-D7 should blink

I can also suggest to try binary micropython 1.14, not the latest versions
I can try the latest on my board and check if I can reproduce the problem

I can be normal the board to become unresponsive if the blink_85f.bit
doesn't provide FPGA connection between usbserial ftdi and esp32.
If blink includes small assigns to route tx/rx ftdi-wifi then board should
continue being responsive. But of course, we need to fix programming
blink first.

**Comment by nullobject** [comment]
@emard Thanks, I will try to downgrade micropython.

**Comment by emard** [comment]
I can confirm same situation as yours,
blue led not going off when esp32ecp5
used with currently latest micropython
esp32-20220618-v1.19.1.bin

I regularly use esp32-idf3-20210202-v1.14.bin
and it works, blue led goes off, SD card can be
mounted, unmounted and mounted again without crash

I should check what's broken with 1.19.1 and get some fix

**Comment by nullobject** [comment]
@emard I can confirm it also works for me with `esp32-idf4-20210202-v1.14.bin`.

**Comment by nullobject** [comment]
Closing this issue.
