### ISSUE TITLE
jtag

### ISSUE THREAD

**Issue by monk31** [emard/esp32ecp5#6]
hello,

your project is interesting because i posted a similar project but with
a machx02
https://github.com/monk31/wifi_lattice

I use the SPI bus from Lattice that  i configure in slave
and it works well

but for the jtag part, i didn't use the spi characteristic in esp32 and
i see that your program work
so i'm curious to your experience with jtag because i didn't make
complete test

**Comment by emard** [comment]
hardware SPI as JTAG works great with help of some luck, otherwise
it wouldn't work so easily.

I had to hack and workaround some glitches during SPI enable/disable
and finally I got very good results at programming ECP5 directly at 30 Mbps
using accelerated ESP32 hardware SPI-JTAG and a bit slower but still nice
programming SPI config FLASH chip attached to ECP5 using
ESP32 software SPI-JTAG.
